### ISSUE TITLE
Please mention how to install on ARM.

### ISSUE THREAD

**Issue by engineerdawood** [VOLTTRON/volttron-docker#34]
Please tell me how to run this on ARM, Thank You.

**Comment by bonicim** [comment]
Hi @engineerdawood, on what device do you want to build and run this container in? Is it a Raspberry Pi 4 or something similar?

**Comment by engineerdawood** [comment]
Hi, @bonicim Thank You very much for replying.

I am using [Jetson Xavier Nx](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-xavier-nx/), [Nano](https://developer.nvidia.com/embedded/jetson-nano-developer-kit), and Pi4 all three. I think all are the same having arm64 I'll prefer any mentioned.

I am getting following Issues:

**On Nano/Xavier**
> Step 1/42 : ARG image_user=amd64
Step 2/42 : ARG image_repo=debian
Step 3/42 : ARG image_tag=buster
Step 4/42 : FROM ${image_user}/${image_repo}:${image_tag} as volttron_base
buster: Pulling from amd64/debian
.
.
.
Step 18/42 : RUN set -eux; apt-get update; apt-get install -y --no-install-recommends     procps     gosu     vim     tree     build-essential     python3-dev     python3-pip     python3-setuptools     python3-wheel     openssl     libssl-dev     libevent-dev     git     gnupg     dirmngr     apt-transport-https     wget     curl     ca-certificates     libffi-dev
 ---> Running in 2adc820481c0
standard_init_linux.go:211: exec user process caused "exec format error"
The command 'bash -c set -eux; apt-get update; apt-get install -y --no-install-recommends     procps     gosu     vim     tree     build-essential     python3-dev     python3-pip     python3-setuptools     python3-wheel     openssl     libssl-dev     libevent-dev     git     gnupg     dirmngr     apt-transport-https     wget     curl     ca-certificates     libffi-dev' returned a non-zero code: 1
ERROR: Service 'volttron1' failed to build

**On Pi4**
> Step 1/42 : ARG image_user=amd64
Step 2/42 : ARG image_repo=debian
Step 3/42 : ARG image_tag=buster
Step 4/42 : FROM ${image_user}/${image_repo}:${image_tag} as volttron_base
buster: Pulling from amd64/debian
e22122b926a1: Pulling fs layer
.
.
.
Step 18/42 : RUN set -eux; apt-get update; apt-get install -y --no-install-recommends     procps     gosu     vim     tree     build-essential     python3-dev     python3-pip     python3-setuptools     python3-wheel     openssl     libssl-dev     libevent-dev     git     gnupg     dirmngr     apt-transport-https     wget     curl     ca-certificates     libffi-dev
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
 ---> Running in 73fb6b2cf41a
standard_init_linux.go:219: exec user process caused: exec format error
The command 'bash -c set -eux; apt-get update; apt-get install -y --no-install-recommends     procps     gosu     vim     tree     build-essential     python3-dev     python3-pip     python3-setuptools     python3-wheel     openssl     libssl-dev     libevent-dev     git     gnupg     dirmngr     apt-transport-https     wget     curl     ca-certificates     libffi-dev' returned a non-zero code: 1
ERROR: Service 'volttron1' failed to build

**Background**
Volttron is our backbone. Local installation and RabbiqMQ installation etc takes a lot of time and error handling.
We will be installing Edge devices on buildings. If we get this Volltron running on Docker over ARM. It will be a miracle for us.

Thank You Very Much.

**Comment by bonicim** [comment]
@engineerdawood  Thanks for the detailed info. I have an Rpi4 and will attempt to replicate your error message and get back to you.

**Comment by GHYOON** [comment]
I think you should change the base image. not amd64

**Comment by craigpnnl** [comment]
To expand you mean during the build you should pass the image_user flag to the built runtime?  @GHYOON correct?

**Comment by engineerdawood** [comment]
> @engineerdawood Thanks for the detailed info. I have an Rpi4 and will attempt to replicate your error message and get back to you.

Thank You Very Much. I'll be waiting.

**Comment by engineerdawood** [comment]
> I think you should change the base image. not amd64

Currently, it's
ARG image_user=amd64

Can you please suggest the exact change it might work?

**Comment by engineerdawood** [comment]
> I think you should change the base image. not amd64

Hi, I changed to
> FROM ubuntu:18.04 as volttron_base

The installation did proceed. But received following error:

> Step 26/42 : RUN pip3 install -e . --user
 ---> Running in 04bb65e2f530
Directory '.' is not installable. File 'setup.py' not found.
The command 'bash -c pip3 install -e . --user' returned a non-zero code: 1
ERROR: Service 'volttron1' failed to build

Please suggest.

**Comment by engineerdawood** [comment]
@bonicim @craig8 
IMPORTANT UPDATE:

Git Cloned the latest repository to my AMD. Run the following command
`docker-compose -f docker-compose-rmq.yml up`
Received Following Error
> Step 26/42 : RUN pip3 install -e . --user
 ---> Running in c464e5c4313e
Directory '.' is not installable. File 'setup.py' not found.
The command 'bash -c pip3 install -e . --user' returned a non-zero code: 1
ERROR: Service 'volttron1' failed to build


Then I took my ARM64 changed
`ARG image_user=amd64`
to
`ARG image_user=arm64v8`
Received same error as above
> Directory '.' is not installable. File 'setup.py' not found.
The command 'bash -c pip3 install -e . --user' returned a non-zero code: 1
ERROR: Service 'volttron1' failed to build

There is another thing I would like to mention on **Line 48**
`RUN mkdir -p /code && chown $VOLTTRON_USER.$VOLTTRON_USER /code \`
has to be
`RUN mkdir -p /code && chown $VOLTTRON_USER**:**$VOLTTRON_USER /code \`
right?


I think now you can debug better.
Thanks

**Comment by engineerdawood** [comment]
I was able to install it successfully on ARM and made multiple raspberry pi 4 as well. Everything worked great, the project was under NDA I don't have access to right now I can't share the solution right away.
Marking as completed.

Thanks

**Comment by craigpnnl** [comment]
@engineerdawood Good job making it work!!  Knowing it does makes it easier to look for solutions :)
