### ISSUE TITLE
Docker installation does not set proper permissions on socket

### ISSUE THREAD

**Issue by jkempf42** [VOLTTRON/volttron-docker#40]
The installation of Docker does not set proper permissions on the socket, and as a result an error message occurs when you try to start docker-compose. The following will fix the problem:

sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker

             jak

**Comment by bonicim** [comment]
Hi @jak42, thank you for opening this issue. The script does have the command to add the current user to the docker group as seen here in line 37: https://github.com/VOLTTRON/volttron-docker/blob/main/docker_install_ubuntu.sh#L37

Can you outline the steps to reproduce this error? Can you also paste the error that you saw? Also, what was the environment that you ran this script in?

**Comment by jkempf42** [comment]
Mark,

Actually, this is a general Docker problem. The Unix socket Docker opens
requires root permissions to use, so the incantation I gave in the bug
report is the recommended way to fix the problem. I didn't use the script
to install Docker, since I was running on Ubuntu 20.04 and not 18.04.

So I think you can just close the bug. Sorry about the confusion.

              jak

**Comment by bonicim** [comment]
@jak42 Thanks for the clarification. Closing issue as requested.
