### ISSUE TITLE
Unable to build Volttron docker image

### ISSUE THREAD

**Issue by yuyi-d** [VOLTTRON/volttron-docker#69]
Failed to build docker image with the following error message.
<img width="620" alt="Screenshot (111)" src="https://user-images.githubusercontent.com/102050610/220433912-431c59a3-cdfd-42db-9381-209b3f7ae3c1.png">

**Comment by acedrew** [comment]
gevent issues say to upgrade to 21.8.0 to fix cython incompatibilities.
Testing with 21.12.0 now
https://github.com/gevent/gevent/issues/1801

**Comment by craigpnnl** [comment]
@yuyi-d what operating system were you using when you built the image?

**Comment by craigpnnl** [comment]
In PR#67 we update the base image to bullseye and you should be able to build it locally now.  Please let us know if this does not work for you.  Also close the issue when done testing.

**Comment by craigpnnl** [comment]
note the #67 was pushed to develop branch so please checkout that locally for testing.

**Comment by yuyi-d** [comment]
@craig8 I tested the develop branch on a Linux machine (Ubuntu 20.04.2) and I was able to build & start the image locally Thank you!

**Comment by craigpnnl** [comment]
@yuyi-d that's great to hear!
